server:
  port: 10000
  servlet:
    context-path: /
spring:
  application:
    name: spring-ai-app
  profiles:
    active: prod
  # MySQL 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testAI?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: cup_dba  # 之前创建的用户
    password: OStem@00  # 对应密码
  jdbc:
    template:
      query-timeout: 30  # 查询超时时间（秒）
