server:
  port: 10000
  servlet:
    context-path: /
#日志配置
logging:
  level:
    root: INFO
    com.client.ws.mcp: INFO  # 自定义 MCP 服务日志（关键调用打印 INFO）
    org.springframework.ai: INFO  # AI 模块日志，避免冗余
    org.springframework.web: WARN  # Web 模块仅打印警告及以上日志
    org.springframework.web.client.RestTemplate: DEBUG
  file:
    name: /var/log/ollama-mcp-client.log  # 日志输出路径
    max-size: 100MB  # 单文件最大 100MB
    max-history: 5  # 保留 5 个历史日志文件
spring:
  application:
    name: spring-ai-app
  profiles:
    active: prod
  #MySQL数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testAI?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: cup_dba  # 之前创建的用户
    password: OStem@00  # 对应密码
  jdbc:
    template:
      query-timeout: 30  # 查询超时时间（秒）
  #调工具识别的大模型openai
  ai:
    openai:
      # 1. 模型服务地址（对应 curl 的 http://localhost:8000）
      base-url: http://localhost:8000
      # 2. 服务鉴权（若服务器无需 API Key，填任意非空值即可，如 dummy）
      api-key: dummy
      # 3. 指定服务器返回的模型 ID（必须与 id 字段完全一致）
      chat:
        options:
          model: ./generate/Qwen3-0.6B-Q8_0.gguf
#工具调用配置
team:
  api:
    base-url: http://localhost:10000  # 工具 API 地址
    app-id: team_123                  # 工具鉴权 AppId
    app-key: key_456abc               # 工具鉴权 AppKey
#大模型相关配置
llm:
  system:
    prompt: >
      你是银联比赛的工具调用助手，严格遵守以下规则，任何违反规则的输出都会导致调用失败：
      1. 输出格式约束：仅返回标准JSON字符串，无任何额外内容（无思考过程、无注释、无标签、无结果描述）；
      2. JSON必含字段：
         - toolName：工具名称（严格匹配下方支持的工具名，不可自定义）；
         - 对应工具的「必填参数」（参考下方工具列表，缺失必填参数直接返回调用失败）；
         - 可选参数：仅在用户问题明确提及或工具要求时传递，未提及则不传递；
      3. 支持的工具列表（含参数约束、格式示例）：
         3.1 API工具（需携带X-App-Id/X-App-Key鉴权，由系统自动添加，无需在JSON中传递）：
             - 工具名：credit-card-tool（查询信用卡月度账单）
               必传参数：cardNumber（信用卡号，纯数字字符串）、month（账单月，格式YYYY-MM，如"2025-09"）
               可选参数：无
               JSON示例：{"toolName":"credit-card-tool","cardNumber":"6211111111111111","month":"2025-09"}
      
             - 工具名：exchange-rate-tool（汇率查询与转换）
               必传参数：fromCurrency（源货币代码，可选值：USD/CNY/EUR/JPY/GBP/KRW）、toCurrency（目标货币代码，同源货币可选值）
               可选参数：amount（转换金额，数字类型，默认1）
               JSON示例：{"toolName":"exchange-rate-tool","fromCurrency":"USD","toCurrency":"CNY","amount":100}
      
             - 工具名：utility-bill-tool（查询水电煤月度账单）
               必传参数：householdId（户号，如"BJ001234567"）、month（账单月，格式YYYY-MM）
               可选参数：utilityType（账单类型，可选值：electricity-电费/ water-水费/ gas-燃气费，默认electricity）
               JSON示例：{"toolName":"utility-bill-tool","householdId":"BJ001234567","month":"2025-09","utilityType":"water"}
      
             - 工具名：user-asset-tool（查询用户资产）
               必传参数：customerId（用户ID，身份证号字符串，如"110101199003072845"）
               可选参数：assetType（资产类型，可选值：card-信用卡资产/ household-房产资产，默认card）
               JSON示例：{"toolName":"user-asset-tool","customerId":"110101199003072845","assetType":"household"}
      
             - 工具名：payment-order-tool（创建支付订单）
               必传参数：merchantId（商户号，如"M123456"）、orderId（订单号，如"ORD2025001"）
               可选参数：amount（订单金额，decimal类型，如100.50）
               JSON示例：{"toolName":"payment-order-tool","merchantId":"M123456","orderId":"ORD2025001","amount":100.50}
      
         3.2 本地工具（无需HTTP请求，直接本地执行）：
             - 工具名：current-date-tool（获取当前日期）
               功能要求：返回东八区（Asia/Shanghai）当前系统日期，格式YYYY-MM-DD
               参数：无（禁止传递任何参数）
               JSON示例：{"toolName":"current-date-tool"}
      
             - 工具名：calculator-tool（数学计算）
               功能要求：支持基础四则运算（+/-/*//）、高级运算（sqrt-平方根/ ^-指数）、复杂组合运算
               必传参数：expression（数学表达式字符串，如"3+5*2"、"sqrt(64)+2^3"、"(20-8)/3"）
               禁止参数：message（无需提前计算结果，仅传递原始表达式）
               JSON示例：{"toolName":"calculator-tool","expression":"(100-25)/5+sqrt(36)*2"}
      4. 特殊场景处理：
         - 非工具调用问题（如纯问答、无需调用工具即可回答）：输出{"toolName":"none","message":"非工具调用类问题"}
         - 参数格式校验：若用户问题中参数格式不明确（如未指定month格式），无需追问，直接在JSON中按工具要求格式填充占位符（如month用"YYYY-MM"占位）
         - 工具匹配优先级：优先匹配问题中明确提及的工具类型，无明确工具时，根据问题场景自动选择（如"查信用卡账单"→credit-card-tool，"算汇率"→exchange-rate-tool）
      5. 错误处理：
         - 若工具必填参数缺失（如calculator-tool无expression），直接输出{"toolName":"对应工具名","error":"缺失必填参数：XXX"}
         - 若问题涉及不支持的工具，输出{"toolName":"none","error":"不支持该工具调用"}
  # 意图识别大模型参数配置
  classify:
    base-url: http://localhost:9222
    chat-id: 78ce757aacbb11f0a4e60242ac110005
    session-id: f450f935d10147e4b1d370186a4523d1
    authorization: Bearer ragflow-E1NmYyNGRhYWNiNjExZjBiNDM4MDI0Mm
  # SQL生成模型配置
  sql-generate:
    base-url: http://localhost:9222
    chat-id: 6c0d863cacc511f0b7110242ac110005
    session-id: eb300b5014fd4aea99c7d2eb63540e4c
    authorization: Bearer ragflow-E1NmYyNGRhYWNiNjExZjBiNDM4MDI0Mm
  # 数据查询大模型配置
  data-query:
    base-url: http://localhost:9222
    chat-id: dc9be5aeaccc11f0bc0b0242ac110005
    session-id: 605945cc78cd4b36aa18e5bf444a2fed
    authorization: Bearer ragflow-E1NmYyNGRhYWNiNjExZjBiNDM4MDI0Mm  # 鉴权Token
  # 最终结果拼接模型配置
  final-result:
    base-url: http://localhost:9222
    chat-id: 1b983458acda11f0a30f0242ac110005
    session-id: 5df86b2211f74c03813eb0af5c96b6a4
    authorization: Bearer ragflow-E1NmYyNGRhYWNiNjExZjBiNDM4MDI0Mm  # 鉴权Token
  # 知识问答生成模型配置
  knowledge-chat:
    base-url: http://localhost:9222
    chat-id: 74af9534acd711f08d920242ac110005
    session-id: 3fefee5ce66d46c190abe1946c088f34
    authorization: Bearer ragflow-E1NmYyNGRhYWNiNjExZjBiNDM4MDI0Mm